/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PortariaRouteImport } from './routes/portaria'
import { Route as PesquisaRouteImport } from './routes/pesquisa'
import { Route as IndexRouteImport } from './routes/index'

const PortariaRoute = PortariaRouteImport.update({
  id: '/portaria',
  path: '/portaria',
  getParentRoute: () => rootRouteImport,
} as any)
const PesquisaRoute = PesquisaRouteImport.update({
  id: '/pesquisa',
  path: '/pesquisa',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pesquisa': typeof PesquisaRoute
  '/portaria': typeof PortariaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pesquisa': typeof PesquisaRoute
  '/portaria': typeof PortariaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pesquisa': typeof PesquisaRoute
  '/portaria': typeof PortariaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pesquisa' | '/portaria'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pesquisa' | '/portaria'
  id: '__root__' | '/' | '/pesquisa' | '/portaria'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PesquisaRoute: typeof PesquisaRoute
  PortariaRoute: typeof PortariaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/portaria': {
      id: '/portaria'
      path: '/portaria'
      fullPath: '/portaria'
      preLoaderRoute: typeof PortariaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pesquisa': {
      id: '/pesquisa'
      path: '/pesquisa'
      fullPath: '/pesquisa'
      preLoaderRoute: typeof PesquisaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PesquisaRoute: PesquisaRoute,
  PortariaRoute: PortariaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
